### ISSUE TITLE
Not an issue per se - more of  a question

### ISSUE THREAD

**Issue by pjhalsli** [axyl-os/axyl-bspwm#5]
I have used bspwm for close to 7 years now - the last 2 years I have used TokyNight so obv your distro drew my attention - looked trough the bspwmrc which was fine - even tho it gives new users some bad habits. My questions though is; where's the sxhkdrc? I'd love to se the keybindings you guys use for different things - I mean it's without a doubt my most important file - so I would love to have a peak at the one you use

edit:
excellent work on the distro btw - you have good taste   ;)

**Comment by adarsh-67r** [comment]
@pjhalsli [Here is the sxhkd config](https://github.com/axyl-os/axyl-skeleton/tree/master/etc/skel/.config/sxhkd)
